sudo: required
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
script:
  - go install github.com/codehand/cest
  - rm -rf test/handler_test.go
  - cest -all test/handler.go
  - go test ./test/... -v