sudo: required
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
script:
  - go install github.com/codehand/cest
  - rm -rf tests
  - rm -rf test/handler_test.go
  - cest -all test/handler.go
  - go fmt
  - go test ./test/... -v
  - go test ./tests/... -v
  - go test ./... 
  - rm -rf tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t b0dcee8f-8bc6-4b57-a476-6bbe559ddfe5