sudo: required
language: go
go:
  # - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
os:
  - linux
  - osx
  - windows
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
script:
  - go install github.com/codehand/cest
  - cd example

  - rm -f **/*_test.go
  - cest -all .
  - go test ./... -v

  - rm -f **/*_test.go
  - cest -all *
  - go test ./... -v

  - rm -f **/*_test.go
  - cest -all ...
  - go test ./... -v

  - rm -f **/*_test.go
  - rm -rf tests
  - cest -all -output=tests ...
  - go test ./... -v

  - rm -f **/*_test.go
  - rm -rf tests
  - cest -only=EchoContext -output=tests handler/abc/abc.go
  - go test ./... -v
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t b0dcee8f-8bc6-4b57-a476-6bbe559ddfe5