// Code generated by "esc -o /Users/tamgh/ws/src/github.com/codehand/cest/cmd/bindata/esc.go -pkg=bindata /Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates"; DO NOT EDIT.

package bindata

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/call.tmpl": {
		name:    "call.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/call.tmpl",
		size:    293,
		modtime: 1573728549,
		compressed: `
H4sIAAAAAAAC/0yOzUpDMRCFX2Uod6FQ5gEEly66kaKi6yF3ejuYpjIZ/xjm3SXxaro6ycnHyec+80EK
wyZRzpsI90+xI+ADJ5YP1tbIAcrZAHf10fQ9WYQZunOZ2+sfCRgxWtxTeqWF7+nE/f57uOprVOa2dpeO
54hkX+6ca8eUysIwyRYmznBzC7gnpRMba11VJonYwv9HQ+5FxZqwGZIudbj0iabXaXz6fmPc1WdSoVlS
BOJgL+N6zZ8AAAD//5cjH10lAQAA
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/function.tmpl": {
		name:    "function.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/function.tmpl",
		size:    4292,
		modtime: 1574848600,
		compressed: `
H4sIAAAAAAAC/9xXS3PbOBI+S7+io4pdpIuBsnt0yoc4dlJ7iJ21vZvDzFQKJpsWJhSgAZq2VSz89yk8
+JJox5mquYwPsgj048OH7q+ppimwFBJhUdYyJ6Hkwtp507yB1yUcnwCzdj5fLqFp2A0auuBrtBaEAWcO
hIZg3jSayzsE9kGt1yjJWNs0zIdBWcAba+feehQjIThy7kLesZsUmvnMJX0QtAJ2hTmKe9TWzmd+WZTA
/mOuSdc5+cVu9aPAqjBhbUbbDULpV8B4Yxc3WkeMI4dZ0/hnd0wPb7vBuOVcUBbxqcvZLg2+73x1qNwx
v3DN10iofTIPjeu7EbABrH0Pn9Av7aEbZBznd4Qad22//DZII/kaXVoh76LzBM0tdi6LnusduiK14V/H
SGV6ztqQ+4Q+Qd4zlM1mni/3MeEz4O0KTV2RafN85ZKeo6xLeYVUa2nOtVaRgwcu6VxruFWqmnaK9Jzn
KxUPrX12EJJQlzzHJiybXIsNmY8SAI7WOT0y5/NR7lyfu5/lEm4uzy6P4X1RhJbKuUHDutudynvPNSAc
Yb5SPjKcgP9+gQ9JOiqK+axUGppGlJAoDey6vg11kkhFLugF/45FmloL3zIgcvXjO9fayHIwb+YQ/1oC
u0jWEruqZULEXLFlXh12OxwiJi8Is2cYnYkSiFjP4KsTkKKCw8PRMjvFUmns90Ov7/KpoFBg1BppJeQd
3HonCFFY9NC+aUbBz1QIn2AajbgxqIldKLoQVUIZaNNuOYK/ZSAI1y5QYE2bDlHv64vNOTtb5p/SPaM2
gbc548Q7k3JN7IsWkspkcYd09H9e1XhZHsPB/a9yET1u1LVv9iRt/SKve404axemBOEJ5d1rc18uvoW3
G/TGXFt7GEsoNiHzSK1t2hBPCPKsaVgYEMfuPoLUsIFMZ32AXp5nE5q99xDzTahse8yvWlB3+pH6Hp/A
4e2W0LDTuixRNy9JGIs7tNmlrLZDwUn31y8lepZS6JARrjcVJ4RFkBmzgNell7Z+J+dVFZafQ7HTYssl
5PSYuar95k7nFeoCHz4oSfhICWZBTj6d32SwWGSuwfqPWFdtBI1mFKM2pNZ9pHizfvuroNUXTqtkseQb
sbz/13KR7hl8RlqpImkBdAbLJXQ2/61Rb5ONuyHTGqRPETAh9U5kQtnu3oy1gFqHsp5i+V2njs5srD0U
WrpMFkPfNRrD7zDeHToLOIGD+wzagXNwv8hG6YTc1N1to9ZOmFm0TvsWaCfnaAT6vR191v6ATROmda4k
CVljPMhUS9mf4fJWFdusZU2omkTFrpAX76sq0a5pVLENqPeFENsDDbXtwIDXs1vvOO+HQktY5LuXzPM/
au5F899v3/qKZB9U0Wq3G5YFJx7K55QbvCZOtQm7DvcJ/G6UZP+Ta67NildJONJh0avvM9CHONYb2rpN
58k+h5vP4uuXj5r+wMfhnnTAxw3mhEUG6nucV0EVWLJzrrSbo+p7N4Rivhtdo59eWFaYEztD3ATy+vj+
1DtzryN4ALL1GHI9bd8R0bnElXQo4Na/TbaIl8t2etMq1uRzwr7fB08pu2/9T4r68dUpPWtH57uBySvP
9fDNsld/hzfkOOVG5INfEJ3CvC6nVN6NxhGGYfNXQuKu2rwYz9+U/9V+xXQRsjGgdIiok5SXiGMLOIL9
XFckNtUIbMTTC+gP1PNJkM/r3F9/L31fEuqffC3lzuclb6U++D/6pXTi1wW4ihr+erBzO5+30+vPAAAA
//8BpV4wxBAAAA==
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/header.tmpl": {
		name:    "header.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/header.tmpl",
		size:    109,
		modtime: 1573613774,
		compressed: `
H4sIAAAAAAAC/zzLMQoCMRCF4X5OMWylTe5hI15hMM/dIIkhpnu8u4sG7H4++MmMR2nw7UBkjE0y63F/
xg4n023lV0vtrzH9ZOSItsPT5SdviUzXqJDWMg/JSLQs2dn++QkAAP//iVIP320AAAA=
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inline.tmpl",
		size:    49,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inputs.tmpl",
		size:    152,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/0yNMQoCQQxFrxKWLSUHEDyAneAJIptZptgomWz1yd1lRoupEh7/vw9sWqopLdU+Z7Ql
E1gLXW/E/a2F7B3Ez/MV2qJlRrDJoRcC1LZ/Zi388GpxH5IOXWzXwcXl0FD/dcX3xsCgfWLyzOcbAAD/
/468z9qYAAAA
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/message.tmpl": {
		name:    "message.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/message.tmpl",
		size:    201,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/results.tmpl": {
		name:    "results.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/results.tmpl",
		size:    168,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates": {
		name:  "templates",
		local: `/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates": {
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/call.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/function.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/header.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inline.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inputs.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/message.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/results.tmpl"],
	},
}
