// Code generated by "esc -o /Users/tamgh/ws/src/github.com/codehand/cest/cmd/bindata/esc.go -pkg=bindata /Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates"; DO NOT EDIT.

package bindata

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/call.tmpl": {
		name:    "call.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/call.tmpl",
		size:    293,
		modtime: 1573728549,
		compressed: `
H4sIAAAAAAAC/0yOzUpDMRCFX2Uod6FQ5gEEly66kaKi6yF3ejuYpjIZ/xjm3SXxaro6ycnHyec+80EK
wyZRzpsI90+xI+ADJ5YP1tbIAcrZAHf10fQ9WYQZunOZ2+sfCRgxWtxTeqWF7+nE/f57uOprVOa2dpeO
54hkX+6ca8eUysIwyRYmznBzC7gnpRMba11VJonYwv9HQ+5FxZqwGZIudbj0iabXaXz6fmPc1WdSoVlS
BOJgL+N6zZ8AAAD//5cjH10lAQAA
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/function.tmpl": {
		name:    "function.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/function.tmpl",
		size:    4269,
		modtime: 1574848438,
		compressed: `
H4sIAAAAAAAC/9xXS3PbOBI+S7+io4pdpIuBsnt0yoc4dlJ7iJ21vZvDzFQKJpsSJySgAZq2VSz89yk8
+JJoxZmquYwPsgj048OH7q+ppskwLwTCIq9FSoUUC2PmTfMGXudwegbMmPl8uYSmYXeo6YpXaAwUGqw5
EGqCedMoLlYI7IOsKhSkjWka5sKgyOCNMXNnPYoREZxY90Ks2F0MzXxmkz4WtAZ2gykWD6iMmc/ccpED
+4++JVWn5Ba71Y8Flpn2azPabhBytwLaGdu4wTpgHDnMmsY922M6eNsNhi3rgiILT13OdmnwfeerRWWP
+YUrXiGhcskcNK5WI2ADWPseLqFb2kM3yDjObwnV9tp++W2QRvAKbdpCrILzBM0tdi6ynusdugK1/l/H
SKl7ztqQ+4Q+Q94BymYzx5f9mPAZ8HaDui5Jt3m+ckGHKOtS3iDVSuhLpWTg4JELulQK7qUsp50CPZfp
WoZD61QVG9IfBQCcVCk9Mbv5Uezck72I5RLuri+uT+F9lvneSblGzbprnErwwBUgnGC6li4ynIH7foWP
UTy6/fkslwqapsghkgrYbX3vCyISkmzQK/4dszg2Br4lQGQLxbWoMYFOb97MIfy1THWRjCF2U4uIiNmq
SpwM7LYyBEyu82cHqJsVORCxnsFXZyCKEo6PR8vsHHOpsN/3Tb3Lp4RMgpYV0roQK7h3TuCjsOChXHeM
gl9IHz7COBhxrVERu5J0VZQRJaB0u2UJ/pZAQVjZQJ41pTtEva+rKutsbZl7iveM2gTO5oIT70zyitgX
VQjKo8UK6eT/vKzxOj+Fo4dfxSJ43Mlb19VR3PoFXvc6btYuTHX+MxK718+uXFyvbjfojLky5jiUUOg2
5pAa07QhnlHeWdMwPwlO7X14TWEDPU76AL0OzybEee8h5JuQ0/aYX1VB3elHMnt6Bsf3W0LNzus8R9W8
JGEobt9m16LcDpUl3l+/FuhYiqFDRlhtSk4IC+XVbAGvc6dh/U7Ky9IvH0Kx02LLJaT0lNiq/WZP5xTq
Ch8/SEH4RBEmXk4+Xd4lsFgktsH6j1BXbQSFehSj1iSrPlK4Wbf9taD1F07raLHkm2L58K/lIt4z+Iy0
llnUAugMlkvobP5bo9pGG3tDujWInyNgQtOtyPiy3b0ZYwCV8mU9xfK7Th2t2Vh7yLd0Hi2GvhVqzVcY
7g6tBZzB0UMC7WQ5elgko3SF2NTdbaNSVphZsI77FmhH5GjWub0dfVbugE3jx3IqBRWixnCQqZYyP8Pl
vcy2SctaIWsqSnaDPHtflpGyTSOzrUe9L4TYHmiobUcanJ7dO8d5PxRawgLfvWRe/lFzJ5r/fvvWVST7
ILNWu+2wzDhxXz7nXOMtcaq137W4z+B3LQX7n6i40mteRv5Ix1mvvgegD3FUG9raTevJPvubT8J7losa
/8DH4p50wKcNpoRZAvJ7mFdeFVi0c664m6PyezeEQr47VaObXpiXmBK7QNx48vr47tQ7c68jeACy9Rhy
PW3fEdG5hJV4KODGvTa2iJfLdnrTOtTkIWHf74PnlN21/idJ/fjqlJ61o/PdwOSV43r4Ctmrv8Xrc5xz
XaSDnwqdwrzOp1TejsYRhmHzl4XAXbV5MZ6/Kf+r/YrpIiRjQPEQUScpLxHHFnAA+7kuqdiUI7ABTy+g
P1DPZ0Ee1rm//l76PidUP/layq3PS95KXfB/9EvpxK8LsBU1/PVg5mY+b6fXnwEAAP//mWvi1K0QAAA=
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/header.tmpl": {
		name:    "header.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/header.tmpl",
		size:    109,
		modtime: 1573613774,
		compressed: `
H4sIAAAAAAAC/zzLMQoCMRCF4X5OMWylTe5hI15hMM/dIIkhpnu8u4sG7H4++MmMR2nw7UBkjE0y63F/
xg4n023lV0vtrzH9ZOSItsPT5SdviUzXqJDWMg/JSLQs2dn++QkAAP//iVIP320AAAA=
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inline.tmpl",
		size:    49,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inputs.tmpl",
		size:    152,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/0yNMQoCQQxFrxKWLSUHEDyAneAJIptZptgomWz1yd1lRoupEh7/vw9sWqopLdU+Z7Ql
E1gLXW/E/a2F7B3Ez/MV2qJlRrDJoRcC1LZ/Zi388GpxH5IOXWzXwcXl0FD/dcX3xsCgfWLyzOcbAAD/
/468z9qYAAAA
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/message.tmpl": {
		name:    "message.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/message.tmpl",
		size:    201,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/results.tmpl": {
		name:    "results.tmpl",
		local:   "/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/results.tmpl",
		size:    168,
		modtime: 1572858974,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates": {
		name:  "templates",
		local: `/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates": {
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/call.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/function.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/header.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inline.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/inputs.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/message.tmpl"],
		_escData["/Users/tamgh/ws/src/github.com/codehand/cest/cmd/templates/results.tmpl"],
	},
}
